# Generated by Django 5.1 on 2024-09-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_remove_shiftdetails_supplier_shift_coffee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
