# Generated by Django 5.1 on 2024-09-16 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_alter_shift_shift_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftBaggingOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_no_bagging_off', models.IntegerField(editable=False, unique=True)),
                ('activity', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftDetailsBaggingOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('total_kgs', models.IntegerField()),
                ('total_bags', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('loss', models.IntegerField(default=0)),
                ('supplier', models.CharField(max_length=255)),
                ('cell', models.CharField(max_length=255)),
                ('stock_card', models.CharField(max_length=255)),
                ('lot_no', models.CharField(default=0, max_length=255)),
                ('batchno_grn', models.CharField(max_length=255)),
                ('parch_grade', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('entry_type', models.CharField(max_length=255)),
                ('shiftbaggingoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shiftbaggingoff')),
            ],
        ),
    ]
