# Generated by Django 5.1 on 2024-09-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_shiftbaggingoff_shiftdetailsbaggingoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftbaggingoff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shiftdetailsbaggingoff',
            name='batchno_grn',
            field=models.CharField(default=67, max_length=255),
        ),
    ]
