# Generated by Django 5.1 on 2024-10-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_shiftbaggingoff_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='crop_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='shiftbaggingoff',
            name='crop_year',
            field=models.IntegerField(default=2024),
        ),
    ]
